In [1]:
import numpy as np

a = np.arange(12).reshape(3,2,-1)

In [2]:
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [7]:
a[:,1,1]

array([ 3,  7, 11])

In [4]:
p = (x for x in range(25))
next(p)

0

In [10]:
q = [1,2,3,3,3,4,3,3,3,100,2,5,2,7]
a = list(set(q))
print(a)
a.sort(key=q.index)
print(a)

[1, 2, 3, 100, 4, 5, 7]
[1, 2, 3, 4, 100, 5, 7]


In [9]:
q.index(100)

9

In [14]:
q = ['红', '白', '红', '白', '红', '白']
a = list(set(q))
print(a)
a = a.sort(key=q.index)
print(q.index('白'))
print(a)

['红', '白']
1
None


In [16]:
a = 'ddfsf sdfsdf   \n'
a.strip()

'ddfsf sdfsdf'

In [22]:
import numpy as np
x = [x for x in range(25)]
a = np.array(x).reshape(5,5)

In [24]:
import pandas as pd
b = pd.DataFrame(a,columns=[x for x in range(5)])

In [27]:
b


2   4
0   2   4
1   7   9
2  12  14
3  17  19
4  22  24

In [28]:
b[[2,4]]

2   4
0   2   4
1   7   9
2  12  14
3  17  19
4  22  24

In [33]:
a = np.arange(20)
b = a.reshape(5,2,2)
print(b)
b.sum(axis=0)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


array([[40, 45],
       [50, 55]])

In [35]:
a = np.array(['你好','我好','大家好','你好'])

In [38]:
b = pd.Series(['你好','我好','大家好','你好'])
b

0     你好
1     我好
2    大家好
3     你好
dtype: object

In [42]:
a = ['你好','我好','大家好','你好']

In [44]:
t= {}
for c,index in zip(a,range(len(a))):
    if c not in t:
        t[c] = []
    if c in a:
        t[c].append(index)

2