In [1]:
import numpy as np

a = np.arange(12).reshape(3,2,-1)

In [13]:
# 上下文管理器
class A:
    def __enter__(self,*args):
        print('创建上下文')
    def __init__(self):
        print('---------------')
    def __exit__(self,*args):
        print('管理器退出')

In [14]:
with A() as a:
    print('执行域')

---------------
创建上下文
执行域
管理器退出


In [2]:
a  =  np.arange(2).reshape(1,2)
a

array([[0, 1]])

In [12]:
# # js
# def counter():
#     i = 0
#     def plus():
#         i = i + 1
#         return i
#     return plus
# a = counter()

In [ ]:
# function counter(){
#     var i = 0;
#     function plus(){
#         ++ i;
#         return i
#     }
#     return plus
# }

In [15]:
a =  {
    'ai':{
        'aj':0.01
    }
}
a['ai']['aj']
# 在python中，可以使用json串来创建字典，json的结构是一个键值对的结构

0.01

In [16]:
a

{'ai': {'aj': 0.01}}

In [4]:
a[:,1,1]

array([ 3,  7, 11])

In [5]:
p = (x for x in range(25))
next(p)

0

In [6]:
q = [1,2,3,3,3,4,3,3,3,100,2,5,2,7]
a = list(set(q))
print(a)
a.sort(key=q.index)
print(a)

[1, 2, 3, 100, 4, 5, 7]
[1, 2, 3, 4, 100, 5, 7]


In [7]:
q.index(100)

9

In [3]:
a = set()

In [12]:
a.add('b')
a.add('a')
a.add('b')
a

{'a', 'b'}

In [8]:
q = ['红', '白', '红', '白', '红', '白']
a = list(set(q))
print(a)
a = a.sort(key=q.index)
print(q.index('白'))
print(a)

['红', '白']
1
None


In [9]:
a = 'ddfsf sdfsdf   \n'
a.strip()

'ddfsf sdfsdf'

In [10]:
import numpy as np
x = [x for x in range(25)]
a = np.array(x).reshape(5,5)

In [11]:
import pandas as pd
b = pd.DataFrame(a,columns=[x for x in range(5)])

In [12]:
b


0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [13]:
b[[2,4]]

2   4
0   2   4
1   7   9
2  12  14
3  17  19
4  22  24

In [14]:
a = np.arange(20)
b = a.reshape(5,2,2)
print(b)
b.sum(axis=0)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


array([[40, 45],
       [50, 55]])

In [35]:
a = np.array(['你好','我好','大家好','你好'])

In [16]:
a = np.arange(10).reshape(2,5)
b = np.arange(10).reshape(2,5)
a,b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

In [42]:
a = np.arange(20).reshape(5,2,-1)
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [46]:
a/a.sum(axis=(1,2)).reshape(-1,1,1)

array([[[0.        , 0.16666667],
        [0.33333333, 0.5       ]],

       [[0.18181818, 0.22727273],
        [0.27272727, 0.31818182]],

       [[0.21052632, 0.23684211],
        [0.26315789, 0.28947368]],

       [[0.22222222, 0.24074074],
        [0.25925926, 0.27777778]],

       [[0.22857143, 0.24285714],
        [0.25714286, 0.27142857]]])

In [38]:
b = pd.Series(['你好','我好','大家好','你好'])
b

0     你好
1     我好
2    大家好
3     你好
dtype: object

In [42]:
a = ['你好','我好','大家好','你好']

In [45]:
t= {}
for c,index in zip(a,range(len(a))):
    if c not in t:
        t[c] = []
    if c in a:
        t[c].append(index)

In [50]:
a = np.zeros((3,3))

In [52]:
b = np.random.random((3,3))

In [54]:
a += b

In [55]:
a

array([[0.96123913, 0.67696978, 0.15925989],
       [0.69909847, 0.15723124, 0.86473853],
       [0.9546461 , 0.13097005, 0.5888596 ]])